### ISSUE TITLE
It is possible to have this module as a ViewComponent?

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe.SimpleContactForm#6]
It is possible to have this module as a `ViewComponent`? So that we can have some content on the contact page.

**Comment by joeaudette** [comment]
ViewComponents are for things that are cross cutting and need to be on multiple pages. This project is designed to provide a simple contact form page not something to put on multiple pages.

You can easily copy the views into your local project and customize them with additional content
